### PR TITLE
Updated Updated Why Choose Us, CTA, and FAQs Sections

### PR DESCRIPTION
**Pull request by Nasrah-muse**
**Asxaabta iga review gareya waxaan wax kasoo badalay  Updated Why Choose Us, CTA, and FAQs Sections ☺️**

### CODE REVIEW

**Review by shiinedev — APPROVED** [review]

**Comment by shiinedev** [comment]
Masha cool wye eng

**Comment by Nasrah-muse** [comment]
Conflict baa galay waan xalinayaa ha aqbalina i.a

**Comment by shiinedev** [comment]
Ok eng

**Comment by Nasrah-muse** [comment]
Waad aqbali kartaa Hdda 🙏

**Comment by aishakayf** [comment]
M.a, eng good job.

**Pull request merged**
