### PR TITLE
Implemented Sign-Up and Sign-In Authentication Flow with User Validation

### PR DESCRIPTION
**Pull request by hayle102**
Implemented authentication flow for sign-up and sign-in functionality.

Sign-up & Sign-in Forms: Created forms for user authentication, including username, phone number, provider selection, and PIN input.

Provider Prefix Update: Implemented dynamic prefix update based on the provider selected (Hormuud, Somtel, Telesom, Golis, Somnet).

Input Validation: Added validation for empty fields (username, phone number, provider, and PIN) during both sign-up and sign-in processes.

User Storage: Integrated chrome.storage.local to handle user data (storing new users and retrieving existing users for sign-in). Implemented checks to ensure phone numbers are unique during registration.

PIN Toggle: Implemented the functionality to show/hide the PIN during input.

UI Enhancements: Added error and success messages to provide feedback to the user for various actions (e.g., incorrect phone number, PIN, or successful account creation).

Auth Form Toggle: Enabled switching between sign-up and sign-in forms with dynamic content updates.

### CODE REVIEW

**Comment by sharafdin** [comment]
@dugsiiyeinc/dhaqsopay-extension-developers dhalinyaro maad review-gareesaan ood aqbashaan ? qofka sameeyay maahee qofka kale review ha siiyo hana aqbalo Insha'Allah!

**Comment by iftiiin** [comment]
Eng review ayaa siyay waaka sugeynaa
Waxaa iskala hadalnay discussion-kanoo furan

**Comment by sharafdin** [comment]
> Eng review ayaa siyay waaka sugeynaa Waxaa iskala hadalnay discussion-kanoo furan

haa sax. review halkaan ka bixiya oo `request changes` dooro hadii aad u dirtay wax soohagaajin Insja'Allah!

**Comment by iftiiin** [comment]
Ok hada kadib pull request-gaa kasameenaa I.a

**Pull request closed without merging**
