### PR TITLE
Cta section

### PR DESCRIPTION
**Pull request by Nasrah-muse**
Screenshot 2024-11-18 194331
waxaan kusoo daray CTA-section #22

### CODE REVIEW

**Comment by shiinedev** [comment]
Cool eng nasro👍

**Review by shiinedev — APPROVED** [review]

**Review by A-M-Ahmed — APPROVED** [review]
Nice and well organized

**Review by sarajohn786 — APPROVED** [review]
M.a eng well done.

**Comment by shiinedev** [comment]
@Nasrah-muse  eng Ana base ka badaly wana aqbalay ee hada kadib iska hubi insha`Allah

**Pull request merged**
