### PR TITLE
Website

### PR DESCRIPTION
**Pull request by Nasrah-muse**

### CODE REVIEW

**Review by sharafdin — COMMENTED** [review]
@Nasrah-muse waad dhameyseen website-ka somhn hadeer waan aqbali karaa ?

**Comment by Nasrah-muse** [comment]
> @Nasrah-muse waad dhameyseen website-ka somhn hadeer waan aqbali karaa ?

Mya eng manan dhameyn

**Comment by sharafdin** [comment]
> > @Nasrah-muse waad dhameyseen website-ka somhn hadeer waan aqbali karaa ?
> 
> Mya eng manan dhameyn

in aad xirto ma aheyn markaad dhameydaan ayaan aqbali laheyn marka waan furaa la soco markaad dhameysaan comment ii reeb Insha'Allah!

**Review by A-M-Ahmed — APPROVED** [review]
Good job.

**Review by sarajohn786 — APPROVED** [review]
Good job dear.

**Review by sarajohn786 — APPROVED** [review]
M.a.
Keep going.

**Review by sharafdin — COMMENTED** [review]
@dugsiiyeinc/dhaqsopay-website-developers dhalinyaro waad dhameyseen ayaan filaa ?

**Comment by A-M-Ahmed** [comment]
Wali bro

**Review by sharafdin — APPROVED** [review]

**Pull request merged**
